"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "./providers";
import ResponsiveAppBar from "@/components/appbar";
import { ThemeProvider, createTheme } from "@mui/material/styles";
import { Provider } from "jotai";
import { useAtomValue } from "jotai";

import { ApolloWrapper } from "../lib/apollo-wrapper";
import { authAtom } from "@/components/atoms/auth";
import React, { Suspense } from "react";
import { Box, CircularProgress } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const darkTheme = createTheme({
  palette: {
    mode: "dark",
  },
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <main>
            <ThemeProvider theme={darkTheme}>
              <ApolloWrapper>
                <Provider>
                  <ResponsiveAppBar />
                  <Suspense
                    fallback={
                      <Box
                        sx={{
                          display: "flex",
                          height: "100vh",
                          alignContent: "center",
                          justifyContent: "center",
                        }}
                      >
                        <CircularProgress />
                      </Box>
                    }
                  >
                    {children}
                  </Suspense>
                </Provider>
              </ApolloWrapper>
            </ThemeProvider>
          </main>
        </NextAuthProvider>
      </body>
    </html>
  );
}
